runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /js
  static_dir: templates/js
- url: /.*
  script: main.app


libraries:
- name: jinja2
  version: latest


skip_files:
- node_modules/
- .git/
